name: Build, install and test
on: push
jobs:
   default:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: python -m pip install --upgrade pip numpy
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install
        run: python -m pip install -v .
      - name: Run tests
        run: |
          cd tests
          pydeb -h
          pydeb -v
          pydeb "Asterias rubens"
          python test_amp.py
